### PR TITLE
Weights for Univariates

### PR DESCRIPTION
**Pull request by itsdebartha**
This PR partially addresses #23 and adds weights for univariate average-shifted histograms.
Jobs done:
* Create a new function `ashw` for univariate weighted average-shifted histograms
* Add tests for them
* Update the documentation

### CODE REVIEW

**Comment by ParadaCarleton** [comment]
@joshday

**Comment by joshday** [comment]
Looks cool!  Give me a chance to play around with the PR, but I'd love to add this feature 👍 .

@ParadaCarleton You don't need to ping me (especially within the same day as the PR!).

**Comment by joshday** [comment]
This is a great start, but there's a few changes I'd like to see:

1. Make `weights` a keyword argument (can default to `nothing`) to the `ash`/`ash!` functions.
2. Allow non-integer weights.  This would require parameterizing the `Ash` struct with the `eltype` of the `counts` field.

I think 1 is what I'd require before merging.  2 Can happen sometime later (by me, you, or anyone else).

**Comment by itsdebartha** [comment]
I made the requested change (only `1`). Is it ok now?

**Comment by joshday** [comment]
I meant to remove `ashw` in favor of:

```Julia
ash(x; weight=nothing, kw...)
```

**Comment by itsdebartha** [comment]
I have made the changes you requested (again, only for `1`). Let me know what you think about this now...

P.S.: Sorry for having to wait so long...

**Comment by joshday** [comment]
Looks good to me.  Thanks for the PR and responding to comments!

**Pull request merged**
