### PR TITLE
Add pdf function to Ash2

### PR DESCRIPTION
**Pull request by Chemical118**
I add pdf function to Ash2 struct.

To estimate the value, I use bilinear interpolation see [the bottom expression](https://en.wikipedia.org/wiki/Bilinear_interpolation#Repeated_linear_interpolation).

### CODE REVIEW

**Comment by joshday** [comment]
Thanks!  Can I be greedy and ask for a few tests?

**Comment by Chemical118** [comment]
Sure. I put an example [here](https://gist.github.com/Chemical118/44eee9e538d030d1c39876c6f8218bff). Please review it.

**Comment by joshday** [comment]
I mean in test/runtests.jl so that it will get tested by CI

**Comment by Chemical118** [comment]
Oops, I misunderstood because it was my first time with julia module. I checked that it passes the test. Please review it again.

**Comment by joshday** [comment]
No worries, thanks for the contribution!  I'll merge when CI goes green.

**Comment by Chemical118** [comment]
@joshday  Could you bump version and close this [issue](https://github.com/joshday/AverageShiftedHistograms.jl/issues/17)?

Thanks for your cool package. Have a good day :)

**Pull request merged**
